const http=require('http');
const fs=require('fs').promises;
const PORT=2001;

const server=http.createServer(async(request,response)=>{
  if(request.url=="/" && request.method=="GET") { 
    try{
  response.setHeader('Content-Type','text/html');
    response.write("Data is being generated by server");
   //console.log("default url:"+request.url+" default method:"+request.method);
response.end("<h2>Welcome to Node Server</h2>");
    }catch(err){
      console.log("Error while sending data:"+err);
    }
  }
  else if(request.url=="/data" && request.method=="GET"){
          response.setHeader('Content-Type','text/html');
         const data= await fs.readFile('student.json',{encoding:'utf-8'});
         const htmldata=`<h2 style=color:red>${data}</h2>`;
         //console.log(data);
          response.end(htmldata);

  }

  else if(request.url=="/data" && request.method=="POST"){
    response.setHeader("Content-Type","application/json");
    response.end(JSON.stringify({
      message:"Data inserted successfully"
    }))
  }


  else if(request.url=="/data" && request.method=="PUT"){
    response.setHeader('Content-Type',"application/json");
    const obj={message:"Hi, data updated successfully"};
    response.end(JSON.stringify(obj));
  }
})

server.listen(PORT,()=>{
  console.log("Server is running on:"+PORT)  
});